### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by topleague** [cjkoepke/five-recent#2]
Hey buddy, 

Just uploaded and activated the plugin. When I clicked on "Edit Five Recent" under Posts, it showed me this error (screenshot below):

https://www.dropbox.com/s/7cja67n43xjaxkx/Screenshot%202017-08-14%2021.44.38.png?dl=0

What could I have done wrong?

**Comment by cjkoepke** [comment]
Hey there, did you happen to build the view layer via terminal? Via the docs:

```bash
yarn install && yarn build
```

**Comment by cjkoepke** [comment]
If that didn't work, you can re-clone the repo as I decided to add the static build folder for those who have trouble building a new instance.

**Comment by topleague** [comment]
Okay. I missed that terminal part. I'll look into the issue now. Thanks!

**Comment by topleague** [comment]
I forgot to mention, I actually opted the first advice: Download the repo and use it as a plugin. I did exactly that but it didn't work. Not familiar with the terminal thingy but will try and see it this works. 

Why wouldn't it work as a normal plugin though?

**Comment by cjkoepke** [comment]
What exactly isn't working? Same error when downloading as a ZIP file? Please make sure that you do indeed have a file located at `/view/build/asset-manifest.json`.

**Comment by topleague** [comment]
> What exactly isn't working? Same error when downloading as a ZIP file?

I downloaded the zipped folder just fine. Was able to upload and activate it tool. 

But  the error occurred only when I click on the Edit Five Recent located under Posts. Screenshot of the error: https://www.dropbox.com/s/7cja67n43xjaxkx/Screenshot%202017-08-14%2021.44.38.png?dl=0

> 
Please make sure that you do indeed have a file located at /view/build/asset-manifest.json.

Okay. I will check this now. Thanks!

**Comment by cjkoepke** [comment]
@topleague Closing this issue, as I'm able to load the plugin fine using the ZIP file. If you are still having problems, however, feel free to keep chatting on this thread and I'll do my best to help you debug your situation.
